#!/usr/bin/bash

function getver() {
  ver=$(git -c 'versionsort.suffix=-' \
    ls-remote --exit-code --refs --sort='version:refname' --tags $2 '*.*.*' \
    | tail --lines=1 \
    | cut --delimiter='/' --fields=3)
    curr=$(cat buildconfig/$1.tag)
  if [[ "$curr" != "$ver" ]]; then
    echo -n "[!] "
  fi
  echo $1 "curr: $curr" latest: $ver
}

getver exchange git://git.taler.net/exchange
getver merchant git://git.taler.net/merchant
getver merchant-demos git://git.taler.net/taler-merchant-demos
getver libeufin git://git.taler.net/libeufin
getver wallet git://git.taler.net/wallet-core
getver gnunet git://git.gnunet.org/gnunet
getver sync git://git.taler.net/sync
getver libmhd git://git.gnunet.org/libmicrohttpd
