FROM docker.io/library/debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

ADD https://github.com/containers/podman/releases/download/v4.3.1/podman-remote-static.tar.gz /tmp/podman-remote-static.tar.gz
RUN tar -xvzf /tmp/podman-remote-static.tar.gz -C /usr/bin/ && \
    rm -f /tmp/podman-remote-static.tar.gz && \
    ln -s /usr/bin/podman-remote-static /usr/bin/podman

WORKDIR /workdir

CMD ["/usr/bin/bash"]
